version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all:
        applies-to: version-updates
        update-types:
          - major
          - minor
          - patch

  # Maintain dependencies for Go CLI
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all:
        applies-to: version-updates
        update-types:
          - major
          - minor
          - patch
