version: "2"

formatters:
  enable:
    - gofmt
    - gofumpt

linters:
  enable:
    - gosec
    - govulncheck
  settings:
    gosec:
      excludes:
        - G304
      severity: high
      confidence: medium
  exclusions:
    rules:
      - path: (.+)_test.go
        linters:
          - gosec
