version: "2"

formatters:
  enable:
    - gofmt
    - gofumpt

linters:
  enable:
    - gosec
    - funcorder

  settings:
    gosec:
      excludes:
        - G304
      severity: high
      confidence: medium

    funcorder:
      constructor: true
      struct-method: true
      alphabetical: false

  exclusions:
    rules:
      - path: (.+)_test.go
        linters:
          - gosec
