package env

import (
	"errors"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

const DefaultFilename = ".env.topo"

const generatedHeader = `# Generated by Topo (https://github.com/arm/topo). Do not edit manually.
# Use 'topo configure' to update project parameters.

`

var escapes = strings.NewReplacer(
	"\\", "\\\\",
	"\"", "\\\"",
	"\n", "\\n",
	"\r", "\\r",
	"\t", "\\t",
)

func ResolveFiles(root string, files []string, skipMissing bool) ([]string, error) {
	var paths []string
	for _, filename := range files {
		path := filepath.Join(root, filename)
		if _, err := os.Stat(path); err == nil {
			paths = append(paths, path)
		} else if errors.Is(err, os.ErrNotExist) {
			if skipMissing {
				continue
			}
			return nil, fmt.Errorf("env file %q does not exist", path)
		} else {
			return nil, fmt.Errorf("failed to check env file: %w", err)
		}
	}
	return paths, nil
}

func SaveFile(path string, values map[string]string) error {
	content, err := encodeFile(values)
	if err != nil {
		return fmt.Errorf("failed to encode env file content: %w", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("failed to write env file: %w", err)
	}
	return nil
}

func encodeFile(values map[string]string) (string, error) {
	var content strings.Builder
	content.WriteString(generatedHeader)
	for _, name := range slices.Sorted(maps.Keys(values)) {
		if name == "" {
			return "", errors.New("env parameter name must not be empty")
		}
		content.WriteString(name)
		content.WriteString("=\"")
		content.WriteString(escapes.Replace(values[name]))
		content.WriteString("\"\n")
	}

	return content.String(), nil
}
