package testutil

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

const testSSHConfig = `Host topo-test-*
    HostName localhost
    UserKnownHostsFile ~/.ssh/topo-test-known-hosts/%n

Host *
`

func requireKnownHostsSSHConfig(t testing.TB, containerName string) {
	t.Helper()
	if _, err := exec.LookPath("ssh"); err != nil {
		t.Skipf("container tests require OpenSSH: %v", err)
	}
	if os.Getenv("SETUP_TEST_SSH") == "1" {
		configureSSH(t)
	}
	home, err := os.UserHomeDir()
	require.NoError(t, err)
	knownHostsDir := filepath.Join(home, ".ssh", "topo-test-known-hosts")
	// #nosec G204 -- containerName is generated by the test helper.
	output, err := exec.Command("ssh", "-G", "root@"+containerName).CombinedOutput()
	require.NoError(t, err, "read SSH configuration: %s", output)
	config := strings.ReplaceAll(string(output), "\r\n", "\n")
	config = strings.ReplaceAll(config, `\`, "/")
	knownHostsFile := filepath.ToSlash(filepath.Join(knownHostsDir, containerName))
	if !strings.Contains(config, "hostname localhost\n") || !strings.Contains(config, "userknownhostsfile "+knownHostsFile+"\n") {
		t.Skip("container tests require SSH setup: rerun with SETUP_TEST_SSH=1")
	}
	info, err := os.Stat(knownHostsDir)
	if os.IsNotExist(err) {
		t.Skip("container tests require SSH setup: rerun with SETUP_TEST_SSH=1")
	}
	require.NoError(t, err)
	require.True(t, info.IsDir(), fmt.Sprintf("%s must be a directory", knownHostsDir))
}

func configureSSH(t testing.TB) {
	t.Helper()
	home, err := os.UserHomeDir()
	require.NoError(t, err)
	sshDir := filepath.Join(home, ".ssh")
	require.NoError(t, os.MkdirAll(filepath.Join(sshDir, "topo-test-known-hosts"), 0o700))
	lock, err := os.OpenFile(filepath.Join(sshDir, "topo-test-config.lock"), os.O_CREATE|os.O_RDWR, 0o600)
	require.NoError(t, err)
	defer func() { require.NoError(t, lock.Close()) }()
	require.NoError(t, lockFile(lock))

	path := filepath.Join(sshDir, "config")
	if _, err := os.Lstat(path); err == nil {
		path, err = filepath.EvalSymlinks(path)
		require.NoError(t, err)
	} else {
		require.True(t, os.IsNotExist(err), "locate SSH config: %v", err)
	}
	content, err := os.ReadFile(path)
	if err != nil {
		require.True(t, os.IsNotExist(err), "read SSH config: %v", err)
	}
	if bytes.Contains(content, []byte(testSSHConfig)) {
		return
	}

	file, err := os.CreateTemp(filepath.Dir(path), ".topo-test-config-*")
	require.NoError(t, err)
	defer func() {
		if err := os.Remove(file.Name()); !os.IsNotExist(err) { // #nosec G703 -- removes our temporary file.
			require.NoError(t, err)
		}
	}()
	_, writeErr := file.Write(append([]byte(testSSHConfig), content...))
	closeErr := file.Close()
	require.NoError(t, writeErr)
	require.NoError(t, closeErr)
	if info, err := os.Stat(path); err == nil {
		require.NoError(t, os.Chmod(file.Name(), info.Mode().Perm())) // #nosec G703 -- preserves permissions on our temporary file.
	} else {
		require.True(t, os.IsNotExist(err), "stat SSH config: %v", err)
	}
	require.NoError(t, os.Rename(file.Name(), path)) // #nosec G703 -- installs our temporary file at the resolved config path.
}

func removeKnownHost(t *testing.T, containerName string) {
	t.Helper()
	home, err := os.UserHomeDir()
	if err != nil {
		t.Errorf("failed to locate SSH directory: %v", err)
		return
	}
	path := filepath.Join(home, ".ssh", "topo-test-known-hosts", containerName)
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		t.Errorf("failed to remove test known-hosts file: %v", err)
	}
}
