package testutil

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func requireSSHConfig(t testing.TB, containerName string) {
	t.Helper()
	if _, err := exec.LookPath("ssh"); err != nil {
		t.Skipf("container tests require OpenSSH: %v", err)
	}
	home, err := os.UserHomeDir()
	require.NoError(t, err)
	knownHostsDir := filepath.Join(home, ".ssh", "topo-test-known-hosts")
	// #nosec G204 -- containerName is generated by the test helper.
	output, err := exec.Command("ssh", "-G", "root@"+containerName).CombinedOutput()
	require.NoError(t, err, "read SSH configuration: %s", output)
	config := strings.ReplaceAll(string(output), "\r\n", "\n")
	config = strings.ReplaceAll(config, `\`, "/")
	knownHostsFile := filepath.ToSlash(filepath.Join(knownHostsDir, containerName))
	if !strings.Contains(config, "hostname localhost\n") || !strings.Contains(config, "userknownhostsfile "+knownHostsFile+"\n") {
		t.Skip("container tests require SSH setup: go run ./internal/testutil/cmd/setup-test-ssh")
	}
	info, err := os.Stat(knownHostsDir)
	if os.IsNotExist(err) {
		t.Skip("container tests require SSH setup: go run ./internal/testutil/cmd/setup-test-ssh")
	}
	require.NoError(t, err)
	require.True(t, info.IsDir(), "test known-hosts path must be a directory")
}
